Use 'action' before 'status' in pair

diff --git a/init b/init
--- a/init
+++ b/init
@@ -50,121 +50,124 @@
 # isofs [LORAM]
 #         do not use squashfs filesystem images, but the cdrom filesystem only
 
-fail()
-{
-echo -e '\033[70G[ \033[1;3'${1:-1mFailed}'\033[0;39m ]'
+
+fail() {
+	echo -e '\033[70G[ \033[1;3'${1:-1mFailed}'\033[0;39m ]'
 }
 
-quit()
-{
-[ -d /mnt$4/etc ] || return
-[ -n "$4" ] || busybox mount /mnt -o remount,ro
-busybox mount --move /run /mnt/${1:-run}
-cat>/run/init<<EOT
+
+quit() {
+	[ -d /mnt$4/etc ] || return
+	[ -n "$4" ] || busybox mount /mnt -o remount,ro
+	busybox mount --move /run /mnt/${1:-run}
+	cat > /run/init <<EOT
 $2
 x=/sbin/switch_root
 [ -x \$x ] && exec \$x mnt $3 /sbin/init
 EOT
-fail 2mDone
-exit
+	fail 2mDone
+	exit
 }
 
-arg()
-{
-grep -q $1 /proc/cmdline
+
+arg() {
+	grep -q $1 /proc/cmdline
 }
 
-got()
-{
-arg $1= && root="$(sed "s/.*$1=\([^ ]*\).*/\1/" </proc/cmdline)"
+
+got() {
+	arg $1= && root="$(sed "s/.*$1=\([^ ]*\).*/\1/" </proc/cmdline)"
 }
 
-msg()
-{
-echo "Switching / to $1..."
+
+msg() {
+	echo "Switching / to $1..."
 }
 
-use()
-{
-got $1 && msg "$1 $root"
+
+use() {
+	got $1 && msg "$1 $root"
 }
 
-mnt()
-{
-r=$(busybox blkid 2> /dev/null | sed "s|\"||g;/${root//[^a-zA-Z0-9]/.}/!d;s|:.*||;q")
-r=${r:-$root}
-if [ ! -b $r ]; then
-	r=${r#/dev/}
-	r=/dev/${r%%/*}
-fi
-d=${root#*$r}
-busybox mount $r $1 && return
-w=$(cat /sys/module/usb_storage/parameters/delay_use)
-w=$((1+${w:-2}))
-echo -n "Sleep $w seconds..."
-sleep $w
-busybox mount $r $1
-}
 
-mod()
-{
-for i in $@; do
-	echo "Loading module: $i"
-	modprobe $i 2>/dev/null || busybox insmod $(find /lib/modules|sed "/$i.ko/!dq")
-done
-}
-
-try()
-{
-if [ ! -d /mnt/etc ] && got cryptoroot; then
-	mod dm-mod dm-crypt aes-256
-	d=${root#/dev/}
-	l=crypto-$d
-	if cryptsetup isLuks $root 2>/dev/null; then
-		cryptsetup luksOpen $root $l
-	else
-		read -st 60 -p "Pass phrase : " p
-		k=$(echo $p|hashalot -x -n 32 sha512)
-		echo 0 $(cat $(find /sys/block|grep /$d/size))\
-		crypt aes-plain $k 0 $root 0|dmsetup create $l
+mnt() {
+	r=$(busybox blkid 2> /dev/null | sed "s|\"||g;/${root//[^a-zA-Z0-9]/.}/!d;s|:.*||;q")
+	r=${r:-$root}
+	if [ ! -b $r ]; then
+		r=${r#/dev/}
+		r=/dev/${r%%/*}
 	fi
-	busybox mount /dev/mapper/$l /mnt
-fi
-got subroot && return
-got loopfs && return
-if [ -d /mnt/etc ]; then
+	d=${root#*$r}
+	busybox mount $r $1 && return
+	w=$(cat /sys/module/usb_storage/parameters/delay_use)
+	w=$((1+${w:-2}))
+	echo -n "Sleep $w seconds..."
+	sleep $w
+	busybox mount $r $1
+}
+
+
+mod() {
 	for i in $@; do
-		cp -a $i /mnt$(dirname $i)
+		echo "Loading module: $i"
+		modprobe $i 2>/dev/null || busybox insmod $(find /lib/modules|sed "/$i.ko/!dq")
 	done
-	quit
-fi
-fail
 }
 
-lvm()
-{
-use lvmroot || return
-mod dm-mod
-vgscan --ignorelockingfailure
-vgchange -ay --ignorelockingfailure
-busybox mount /dev/mapper/$root /mnt
-try /dev/mapper $1
+
+try() {
+	if [ ! -d /mnt/etc ] && got cryptoroot; then
+		mod dm-mod dm-crypt aes-256
+		d=${root#/dev/}
+		l=crypto-$d
+		if cryptsetup isLuks $root 2>/dev/null; then
+			cryptsetup luksOpen $root $l
+		else
+			read -st 60 -p "Pass phrase : " p
+			k=$(echo $p|hashalot -x -n 32 sha512)
+			echo 0 $(cat $(find /sys/block|grep /$d/size))\
+			crypt aes-plain $k 0 $root 0|dmsetup create $l
+		fi
+		busybox mount /dev/mapper/$l /mnt
+	fi
+	got subroot && return
+	got loopfs && return
+	if [ -d /mnt/etc ]; then
+		for i in $@; do
+			cp -a $i /mnt$(dirname $i)
+		done
+		quit
+	fi
+	fail
 }
 
-ldraid()
-{
-while read l; do
-	case "$l" in
-		*raid10*)	mod raid10;;
-		*raid0*)	mod raid0;;
-		*raid1*)	mod raid1;;
-		*raid*)		mod raid456;;
-		*mirror*)	mod dm-mirror;;
-	esac
-done
+
+lvm() {
+	use lvmroot || return
+	mod dm-mod
+	vgscan --ignorelockingfailure
+	vgchange -ay --ignorelockingfailure
+	busybox mount /dev/mapper/$root /mnt
+	try /dev/mapper $1
 }
 
-if [ "$1" != "log" ]; then
+
+ldraid() {
+	while read l; do
+		case "$l" in
+			*raid10*)	mod raid10;;
+			*raid0*)	mod raid0;;
+			*raid1*)	mod raid1;;
+			*raid*)		mod raid456;;
+			*mirror*)	mod dm-mirror;;
+		esac
+	done
+}
+
+
+
+
+if [ "$1" != 'log' ]; then
 	busybox mount -t proc proc /proc
 	busybox mount -t sysfs sys /sys
 	busybox mount -t tmpfs tmpfs /run
@@ -175,6 +178,7 @@ if [ "$1" != "log" ]; then
 	. /run/init
 	sh
 fi
+
 for i in /sys/block/*/dev /sys/block/*/*/dev ; do
 	[ -s "$i" ] || continue
 	n=${i%/dev}
@@ -183,9 +187,12 @@ for i in /sys/block/*/dev /sys/block/*/*/dev ; do
 	echo "Create $n "
 	mknod $n b $(sed 's/:/ /' < $i)
 done
+
 got modprobe && mod ${root//,/ }
+
 [ -d /proc/sys/dev/cdrom ] &&
 	ln -s $(sed '/name/!d;s/.*:[^a-z]*//' /proc/sys/dev/cdrom/info) /dev/cdrom
+
 if use dmraid; then
 	dmraid -s | sed '/^type/!ds/.*: *//' | ldraid
 	[ ${root:0:4} = /dev ] ||
@@ -209,6 +216,7 @@ if use softraid; then
 	lvm /etc/mdadm.conf
 fi
 lvm
+
 if got mount; then
 	dev=$root
 	x=$(busybox blkid|grep $dev|sed 's/:.*//;q')
@@ -219,6 +227,7 @@ if got mount; then
 	arg posixovl && echo "And posixovl..." &&
 	mount.posixovl -F /mnt -- -oallow_other -odefault_permissions -osuid
 fi
+
 got loopfs && echo "Into file $root..." &&
 	losetup /dev/loop0 /mnt/$root && busybox mount /dev/loop0 /mnt
 got bindfs && echo "Bind ${root/,/ to }..." &&
@@ -242,17 +251,17 @@ root=90%
 got rootfssize
 [ $(busybox free|busybox awk '/Mem:/{print int(($4*100)/$3)}') -ge $r ] &&
 	busybox mount -t tmpfs -o size=$root,nr_inodes=$inodes tmpfs /mnt &&
-for i in $(ls -ar /); do
-	case "$i" in
-	.*|cdrom)	;;
-	mnt|proc|sys)	mkdir /mnt/$i;;
-	usr|var|rootfs*) mv /$i /mnt;;
-	*)	cp -a /$i /mnt 2>/dev/null && continue
-		fail
-		busybox umount /mnt
-		exit
-	esac
-done || fail 3mSkipped
+	for i in $(ls -ar /); do
+		case "$i" in
+			.*|cdrom)	;;
+			mnt|proc|sys)	mkdir /mnt/$i;;
+			usr|var|rootfs*) mv /$i /mnt;;
+			*)	cp -a /$i /mnt 2>/dev/null && continue
+				fail
+				busybox umount /mnt
+				exit
+		esac
+	done || fail 3mSkipped
 quit
 mod squashfs 2>/dev/null || exit
 msg aufs
